plugins:
  - redocly/redocly_sfti_rules.js

apis:  
  level1:
    root: ../src/CardInfoAPI.yaml
    decorators:
      filter-out:
        property: x-api-level
        value: 
          - 2
      sfti/schema-required:
        level: 1
        stripMarker: true
  level2:
    root: ../src/CardInfoAPI.yaml
    decorators:
      sfti/schema-required:
        level: 2
        stripMarker: true
      sfti/strip-x-api-level: on

# redocly bundle level1 --config .github/redocly.yaml --output cardInfoAPI-level1.yaml
# redocly bundle level2 --config .github/redocly.yaml --output cardInfoAPI-level2.yaml