openapi: 3.1.0
info:
  version: 1.0.0
  title: Common Card API
  description: |
    This specification defines a common card API for payment cards used in Switzerland. The API is supposed to be used by third parties to
    retrieve payment card information for scheme-based debit, credit or prepaid cards (read only).
  contact:
    email: info@common-api.ch
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://card.common-api.ch
security: []
tags:
  - name: Card-tokens
    description: Operations for retrieving information about tokens associated with payment cards.
  - name: Cards
    description: Operations for retrieving information about payment cards.
  - name: Transactions
    description: Operations for retrieving information about transactions and authorizations done with payment cards or tokens.
externalDocs:
  description: Find out more about SFTI API specifications.
  url: https://www.common-api.ch
paths:
  /cards:
    get:
      summary: Provides a list of cards which match the provided query parameters
      description: |
        This operation enables the retrieval of a list of payment cards. Payment cards can be physical or virtual cards. In order to prevent
        API consumers from having to fulfill PCI DSS requirements, no full PAN or other data relevant for this regulation are included. The
        API consumer is expected to have a non-card related identifier for the customer for whom data should be returned (e.g. card account
        number, bank account number).
      operationId: listCards
      tags:
        - Cards
      parameters:
        - $ref: '#/components/parameters/card_status'
        - $ref: '#/components/parameters/cursor'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/client'
        - $ref: '#/components/parameters/correlation'
        - $ref: '#/components/parameters/agent'
      responses:
        '200':
          description: |
            Payment cards were found which match the query parameters. If no cards matched the parameters or access rights are missing, an
            empty list is returned.
          headers:
            X-Correlation-ID:
              $ref: '#/components/headers/X-Correlation-ID'
            X-Next-Cursor:
              $ref: '#/components/headers/X-Next-Cursor'
          content:
            application/json:
              schema:
                type: object
                required:
                  - cards
                properties:
                  cards:
                    type: array
                    items:
                      $ref: '#/components/schemas/CardDetails'
        '400':
          $ref: '#/components/responses/standard400'
        '500':
          $ref: '#/components/responses/standard500'
  /card-accounts:
    x-api-level: 2
    get:
      summary: Provides a list of card accounts which match the provided query parameters
      description: |
        This operation enables the retrieval of a list of card accounts. A card account represents the account to which one or more payment
        cards are linked. In order to prevent API consumers from having to fulfill PCI DSS requirements, no full PAN or other data relevant
        for this regulation are included. The API consumer is expected to have a non-card related identifier for the customer for whom data
        should be returned (e.g. bank account number).
      operationId: listCardAccounts
      tags:
        - Cards
      parameters:
        - $ref: '#/components/parameters/card_status'
        - $ref: '#/components/parameters/cursor'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/client'
        - $ref: '#/components/parameters/correlation'
        - $ref: '#/components/parameters/agent'
      responses:
        '200':
          description: |
            Card accounts were found which match the query parameters. If no card accounts matched the parameters or access rights are missing,
            an empty list is returned.
          headers:
            X-Correlation-ID:
              $ref: '#/components/headers/X-Correlation-ID'
            X-Next-Cursor:
              $ref: '#/components/headers/X-Next-Cursor'
          content:
            application/json:
              schema:
                type: object
                required:
                  - cardAccounts
                properties:
                  cardAccounts:
                    type: array
                    items:
                      $ref: '#/components/schemas/CardDetails'
        '400':
          $ref: '#/components/responses/standard400'
        '500':
          $ref: '#/components/responses/standard500'
components:
  schemas:
    CardStatus:
      title: Card status
      description: |
        Effective status of the card to indicate whether it can be used for payments; definition of enums:
        - active: authorizations are possible
        - suspended: authorizations are temporarily not possible
        - blocked: authorizations are permanently not possible because the card was cancelled or permanently blocked for other reasons
      type: string
      enum:
        - active
        - suspended
        - blocked
      examples:
        - active
    Correlation:
      title: Shared correlation
      description: |
        Schema for X-Correlation-ID header. The correlation value is a unique value to trace API calls across multiple systems, and used e.g. for
        debugging.
      type: string
      examples:
        - f058ebd6-02f7-4d3f-942e-904344e8cde5
    CardDetails:
      CardDetails:
        title: Card details
        description: Describes a payment card with its relevant characteristics.
        allOf:
          - $ref: '#/CardDetailsLevel1'
          - $ref: '#/CardDetailsLevel2'
      CardDetailsLevel1:
        type: object
        required:
          - card_account_currency
          - card_id
          - card_limit_cycle
          - card_limit_daily
          - card_product_code
          - card_product_name
          - card_status
          - cardholder_reference
          - contract_reference
          - embossing_line_1
          - embossing_line_2
          - expiry_date
          - image
          - issuer_code
          - issuer_name
          - issuing_type
          - language
          - pan_4_digits
          - product_line
          - product_type
          - scheme
        properties:
          card_account_currency:
            $ref: ./CardAccountCurrency.yaml
          card_id:
            $ref: ./CardId.yaml
          card_limit_cycle:
            $ref: ./CardLimitCycle.yaml
          card_limit_daily:
            $ref: ./CardLimitDaily.yaml
          card_product_code:
            $ref: ./CardProductCode.yaml
          card_product_name:
            $ref: ./CardProductName.yaml
          card_status:
            $ref: ./CardStatus.yaml
          cardholder_reference:
            $ref: ./CardholderReference.yaml
          contract_reference:
            $ref: ./ContractReference.yaml
          embossing_line_1:
            $ref: ./EmbossingLine1.yaml
          embossing_line_2:
            $ref: ./EmbossingLine2.yaml
          expiry_date:
            $ref: ./ExpiryDate.yaml
          image:
            $ref: ./Image.yaml
          issuer_code:
            $ref: ./IssuerCode.yaml
          issuer_name:
            $ref: ./IssuerName.yaml
          issuing_type:
            $ref: ./IssuingType.yaml
          language:
            $ref: ./Language.yaml
          pan_4_digits:
            $ref: ./Pan4Digits.yaml
          product_line:
            $ref: ./ProductLine.yaml
          product_type:
            $ref: ./ProductType.yaml
          scheme:
            $ref: ./Scheme.yaml
          bank_account_reference:
            $ref: ./BankAccountReference.yaml
          card_account_reference:
            $ref: ./CardAccountReference.yaml
          category:
            $ref: ./Category.yaml
          distribution_partner_code:
            $ref: ./DistributionPartnerCode.yaml
          distribution_partner_name:
            $ref: ./DistributionPartnerName.yaml
          initial_issuing_date:
            $ref: ./InitialIssuingDate.yaml
      CardDetailsLevel2:
        x-api-level: 2
        type: object
        required:
          - cardAccountId
          - personId
        properties:
          cardAccountId:
            $ref: ./CardAccountId.yaml
          personId:
            $ref: ./PersonId.yaml
          contractId:
            $ref: ./ContractId.yaml
    CommonErrorResponse:
      title: Common Error Response
      description: General error response structure used in different response codes.
      type: object
      properties:
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
          examples:
            - Detailed problem description with respect to the current request
        instance:
          type: string
          description: A (relative) URI reference that identifies the specific occurrence of the problem.
          examples:
            - path/to/corresponding/resource
        title:
          type: string
          description: A short, human-readable summary of the problem type.
          examples:
            - This is the general problem description
        type:
          type: string
          description: |
            A URI reference that identifies the problem type. When "about:blank" is used, the title SHOULD be the same as the recommended HTTP
            status phrase for that code (e.g., "Not Found" for 404, and so on).
          examples:
            - about:blank
  parameters:
    card_status:
      in: query
      name: card_status
      description: Retrieves all cards in a certain status. Only one status can be filtered at a time.
      required: false
      schema:
        $ref: '#/components/schemas/CardStatus'
    cursor:
      in: query
      name: cursor
      description: Optional parameter for pagination. An opaque string value used for pagination.
      required: false
      schema:
        type: string
        examples:
          - cursorIDxyz
    limit:
      in: query
      name: limit
      description: Optional parameter for pagination. Maximum number of entries to be returned.
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
        examples:
          - 25
    client:
      in: header
      name: X-CorAPI-Client-ID
      description: ID of the client forwarded to the provider.
      required: false
      schema:
        type: string
    correlation:
      in: header
      name: X-Correlation-ID
      description: Unique ID (defined by the caller) which will be reflected back in the response.
      required: false
      schema:
        $ref: '#/components/schemas/Correlation'
    agent:
      in: header
      name: User-Agent
      description: Name and version of the of the Client software.
      required: false
      schema:
        type: string
  headers:
    X-Correlation-ID:
      schema:
        $ref: '#/components/schemas/Correlation'
      description: Client defined ID from request to correlates HTTP requests between a client and server.
    X-Next-Cursor:
      description: An opaque string value, or an empty string if there are no more results.
      schema:
        type: string
        examples:
          - cursorIDxyz
    Content-Language:
      schema:
        type: string
        examples:
          - en
      description: Language of provided content.
  responses:
    standard400:
      headers:
        Content-Language:
          $ref: '#/components/headers/Content-Language'
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: |
        Client Error - The request could not be processed due to a problem in the data provided. This could be for any of the reasons of the HTML
        standard that would result in a 4xx code.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/CommonErrorResponse'
    standard500:
      headers:
        Content-Language:
          $ref: '#/components/headers/Content-Language'
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: |
        Internal Server Error - The request could not be processed due to a problem at the data provider. This could be for any of the reasons of
        the HTML standard that would result in a 5xx code.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/CommonErrorResponse'
