openapi: 3.1.0
info:
  version: 1.0.0
  title: Common Card API
  description: |
    This specification defines a common card API for payment cards used in Switzerland. The API is supposed to be used by third parties to
    retrieve payment card information for scheme-based debit, credit or prepaid cards (read only).
  contact:
    email: info@common-api.ch
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://card.common-api.ch
security: []
tags:
  - name: Card-tokens
    description: Operations for retrieving information about tokens associated with payment cards.
  - name: Cards
    description: Operations for retrieving information about payment cards.
  - name: Transactions
    description: Operations for retrieving information about transactions and authorizations done with payment cards or tokens.
externalDocs:
  description: Find out more about SFTI API specifications.
  url: https://www.common-api.ch
paths:
  /cards:
    get:
      summary: Provides a list of cards which match the provided query parameters
      description: |
        This operation enables the retrieval of a list of payment cards. Payment cards can be physical or virtual cards. In order to prevent
        API consumers from having to fulfill PCI DSS requirements, no full PAN or other data relevant for this regulation are included. The
        API consumer is expected to have a non-card related identifier for the customer for whom data should be returned (e.g. card account
        number, bank account number).
      operationId: listCards
      tags:
        - Cards
      parameters:
        - $ref: '#/components/parameters/card_status'
        - $ref: '#/components/parameters/cursor'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/client'
        - $ref: '#/components/parameters/correlation'
        - $ref: '#/components/parameters/agent'
      responses:
        '200':
          description: |
            Payment cards were found which match the query parameters. If no cards matched the parameters or access rights are missing, an
            empty list is returned.
          headers:
            X-Correlation-ID:
              $ref: '#/components/headers/X-Correlation-ID'
            X-Next-Cursor:
              $ref: '#/components/headers/X-Next-Cursor'
          content:
            application/json:
              schema:
                type: object
                required:
                  - cards
                properties:
                  cards:
                    type: array
                    items:
                      $ref: '#/components/schemas/CardDetails'
        '400':
          $ref: '#/components/responses/standard400'
        '500':
          $ref: '#/components/responses/standard500'
components:
  schemas:
    CardStatus:
      title: Card status
      description: |
        Effective status of the card to indicate whether it can be used for payments; definition of enums:
        - active: authorizations are possible
        - suspended: authorizations are temporarily not possible
        - blocked: authorizations are permanently not possible because the card was cancelled or permanently blocked for other reasons
      type: string
      enum:
        - active
        - suspended
        - blocked
      examples:
        - active
    Correlation:
      title: Shared correlation
      description: |
        Schema for X-Correlation-ID header. The correlation value is a unique value to trace API calls across multiple systems, and used e.g. for
        debugging.
      type: string
      examples:
        - f058ebd6-02f7-4d3f-942e-904344e8cde5
    Currency:
      description: Currency in ISO code format.
      type: string
      pattern: ^[A-Z]{3}$
      examples:
        - CHF
        - EUR
    Id:
      title: Shared id
      description: Unique identifier to referenece resources.
      type: string
      format: uuid
      maxLength: 50
      examples:
        - eb404f8d-656b-4e51-8872-88c42fa55536
    CardLimitCycle:
      title: Card limit cycle
      description: |
        Total amount of authorizations possible for the card per settlement cycle / month in the currency of the card; effective limit is provided
        that considers limits on the card and relationship; does not indicate the actually available amount for authorizations in the current
        cycle.
      type: integer
      format: int32
      examples:
        - 2000
    CardLimitDaily:
      title: Card limit daily
      description: |
        Total amount of authorizations possible for the card per day in the currency of the card; effective limit is provided that considers
        limits on the card and relationship; does not indicate the actually available amount for authorizations on the current day.
      type: integer
      format: int32
      examples:
        - 2000
    CardProductCode:
      title: Product code
      description: Identifier for the card product.
      type: string
      maxLength: 50
      examples:
        - '1234567'
    CardProductName:
      title: Product name
      description: Name for the card product assigned by the issuer.
      type: string
      maxLength: 100
      examples:
        - A1
        - MC/VI Gold CHF
    CardholderReference:
      title: Cardholder reference
      description: Reference to the cardholder who owns the card which was used for the transaction.
      type: string
      maxLength: 50
      examples:
        - '123456789'
    ContractReference:
      title: Contract reference
      description: Functional reference to a customer relationship/contract that is responsible for the card, defined by the Card Service Provider.
      type: string
      maxLength: 50
      examples:
        - CH3456789012345678901
        - ABC-56789012345
    EmbossingLine1:
      title: Embossing line 1
      description: First line embossed on the card to indicate the cardholder.
      type: string
      maxLength: 35
      examples:
        - Peter Schweizer
    EmbossingLine2:
      title: Embossing line 2
      description: Second line embossed on the card to indicate the cardholder.
      type: string
      maxLength: 35
      examples:
        - Peter Schweizer
    Date:
      title: Shared date
      description: General date that is used for different attributes, format is 'YYYY-MM-DD'.
      type: string
      format: date
      examples:
        - '2018-04-13'
    Image:
      description: URL reference to an image for the design of the card.
      type: string
      format: uri
      examples:
        - https://issuer.ch/public/media/images/card_image.png
    IssuerCode:
      title: Issuer code
      description: Identifier for the legal issuer of a card; responsible towards the schemes for keeping the rules.
      type: string
      maxLength: 50
      examples:
        - '123456789'
    IssuerName:
      title: Issuer name
      description: Name of the legal issuer of a card.
      type: string
      maxLength: 100
      examples:
        - Viseca Card Services
        - UBS
        - Zürcher Kantonalbank
    IssuingType:
      title: Issuing type
      description: |
        Specifies in which form the card is issued; definition of enums:
        - physical: the card is being embossed on a physical material and delivered to the cardholder by mail
        - virtual: the card is being issued only virtually for digital usage
      type: string
      enum:
        - physical
        - virtual
      examples:
        - physical
    Language:
      description: Preferred language of the cardholder for any communication.
      type: string
      enum:
        - de
        - en
        - fr
        - it
      examples:
        - de
    Pan4Digits:
      title: Pan 4 digits
      description: Last 4 digits of the PAN; values can change for the same Card id during the lifecycle.
      type: string
      maxLength: 4
      pattern: ^\d{4}$
      examples:
        - '4321'
    ProductLine:
      title: Product line
      description: Customer segment to which the card is offered.
      type: string
      enum:
        - consumer
        - business
        - corporate
      examples:
        - consumer
    ProductType:
      title: Product type
      description: Type of the card product.
      type: string
      enum:
        - credit
        - debit
        - prepaid
      examples:
        - credit
    Scheme:
      description: Card network which is used to process payments.
      type: string
      enum:
        - mastercard
        - visa
        - americanexpress
        - dinersclub
      examples:
        - mastercard
    ContractId:
      title: Contract Id
      description: |
        Technical reference to a customer relationship, can be used to call the endpoint for contract information.
      type: string
      maxLength: 50
      examples:
        - UUID
    PersonId:
      title: Person Id
      description: |
        Technical reference to a cardholder, can be used to call the endpoint for cardholder information.
      type: string
      maxLength: 50
      examples:
        - UUID
    BankAccountReference:
      title: Bank account reference
      description: |
        Functional reference to the bank account linked to a card; mainly relevant for debit cards, can be empty for credit or prepaid cards.
      type: string
      maxLength: 34
      examples:
        - CH3456789012345678901
    CardAccountReference:
      title: Card account reference
      description: |
        Technical reference to the card account which is used to settle the transactions of the card; can be empty for debit cards which are
        settled directly to the bank account.
      type: string
      maxLength: 50
      examples:
        - AB-4567890123456
    Category:
      description: |
        Identifies the nature of the card in regards to the overall account; for some issuers the Category has an influence on the effect of
        certain lifecycle use cases.
      type: string
      enum:
        - primary_card
        - additional_card
      examples:
        - primary_card
    DistributionPartnerCode:
      title: Distribution partner code
      description: |
        Identifier for the organization which is distributing / selling cards to end customers and who can define the services and branding of the
        card; empty if the card is distributed by the issuer.
      type: string
      maxLength: 50
      examples:
        - '123456789'
    DistributionPartnerName:
      title: Distribution partner name
      description: |
        Name of the organization which is distributing / issuing cards to end customers and who can define the services and branding of the card;
        empty if the card is distributed by the issuer.
      type: string
      maxLength: 100
      examples:
        - Zürcher Kantonalbank
    CardAccountId:
      title: Card account Id
      description: |
        Technical reference to a card account, used as identifier to retrieve card account details via API endpoint.
      type: string
      maxLength: 50
      examples:
        - eb404f8d-656b-4e51-8872-88c42fa55536
    CardDetails:
      title: Card details
      description: Describes a payment card with its relevant characteristics.
      type: object
      required:
        - card_account_currency
        - card_id
        - card_limit_cycle
        - card_limit_daily
        - card_product_code
        - card_product_name
        - card_status
        - cardholder_reference
        - contract_reference
        - embossing_line_1
        - embossing_line_2
        - expiry_date
        - image
        - issuer_code
        - issuer_name
        - issuing_type
        - language
        - pan_4_digits
        - product_line
        - product_type
        - scheme
      properties:
        card_account_currency:
          $ref: '#/components/schemas/Currency'
        card_id:
          $ref: '#/components/schemas/Id'
        card_limit_cycle:
          $ref: '#/components/schemas/CardLimitCycle'
        card_limit_daily:
          $ref: '#/components/schemas/CardLimitDaily'
        card_product_code:
          $ref: '#/components/schemas/CardProductCode'
        card_product_name:
          $ref: '#/components/schemas/CardProductName'
        card_status:
          $ref: '#/components/schemas/CardStatus'
        cardholder_reference:
          $ref: '#/components/schemas/CardholderReference'
        contract_reference:
          $ref: '#/components/schemas/ContractReference'
        embossing_line_1:
          $ref: '#/components/schemas/EmbossingLine1'
        embossing_line_2:
          $ref: '#/components/schemas/EmbossingLine2'
        expiry_date:
          $ref: '#/components/schemas/Date'
        image:
          $ref: '#/components/schemas/Image'
        issuer_code:
          $ref: '#/components/schemas/IssuerCode'
        issuer_name:
          $ref: '#/components/schemas/IssuerName'
        issuing_type:
          $ref: '#/components/schemas/IssuingType'
        language:
          $ref: '#/components/schemas/Language'
        pan_4_digits:
          $ref: '#/components/schemas/Pan4Digits'
        product_line:
          $ref: '#/components/schemas/ProductLine'
        product_type:
          $ref: '#/components/schemas/ProductType'
        scheme:
          $ref: '#/components/schemas/Scheme'
        contract_id:
          $ref: '#/components/schemas/ContractId'
        person_id:
          $ref: '#/components/schemas/PersonId'
        bank_account_reference:
          $ref: '#/components/schemas/BankAccountReference'
        card_account_reference:
          $ref: '#/components/schemas/CardAccountReference'
        category:
          $ref: '#/components/schemas/Category'
        distribution_partner_code:
          $ref: '#/components/schemas/DistributionPartnerCode'
        distribution_partner_name:
          $ref: '#/components/schemas/DistributionPartnerName'
        initial_issuing_date:
          $ref: '#/components/schemas/Date'
        card_account_id:
          $ref: '#/components/schemas/CardAccountId'
    CommonErrorResponse:
      title: Common Error Response
      description: General error response structure used in different response codes.
      type: object
      properties:
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
          examples:
            - Detailed problem description with respect to the current request
        instance:
          type: string
          description: A (relative) URI reference that identifies the specific occurrence of the problem.
          examples:
            - path/to/corresponding/resource
        title:
          type: string
          description: A short, human-readable summary of the problem type.
          examples:
            - This is the general problem description
        type:
          type: string
          description: |
            A URI reference that identifies the problem type. When "about:blank" is used, the title SHOULD be the same as the recommended HTTP
            status phrase for that code (e.g., "Not Found" for 404, and so on).
          examples:
            - about:blank
  parameters:
    card_status:
      in: query
      name: card_status
      description: Retrieves all cards in a certain status. Only one status can be filtered at a time.
      required: false
      schema:
        $ref: '#/components/schemas/CardStatus'
    cursor:
      in: query
      name: cursor
      description: Optional parameter for pagination. An opaque string value used for pagination.
      required: false
      schema:
        type: string
        examples:
          - cursorIDxyz
    limit:
      in: query
      name: limit
      description: Optional parameter for pagination. Maximum number of entries to be returned.
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
        examples:
          - 25
    client:
      in: header
      name: X-CorAPI-Client-ID
      description: ID of the client forwarded to the provider.
      required: false
      schema:
        type: string
    correlation:
      in: header
      name: X-Correlation-ID
      description: Unique ID (defined by the caller) which will be reflected back in the response.
      required: false
      schema:
        $ref: '#/components/schemas/Correlation'
    agent:
      in: header
      name: User-Agent
      description: Name and version of the of the Client software.
      required: false
      schema:
        type: string
  headers:
    X-Correlation-ID:
      schema:
        $ref: '#/components/schemas/Correlation'
      description: Client defined ID from request to correlates HTTP requests between a client and server.
    X-Next-Cursor:
      description: An opaque string value, or an empty string if there are no more results.
      schema:
        type: string
        examples:
          - cursorIDxyz
    Content-Language:
      schema:
        type: string
        examples:
          - en
      description: Language of provided content.
  responses:
    standard400:
      headers:
        Content-Language:
          $ref: '#/components/headers/Content-Language'
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: |
        Client Error - The request could not be processed due to a problem in the data provided. This could be for any of the reasons of the HTML
        standard that would result in a 4xx code.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/CommonErrorResponse'
    standard500:
      headers:
        Content-Language:
          $ref: '#/components/headers/Content-Language'
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: |
        Internal Server Error - The request could not be processed due to a problem at the data provider. This could be for any of the reasons of
        the HTML standard that would result in a 5xx code.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/CommonErrorResponse'
