openapi: 3.1.0
info:
  version: 0.8.0
  title: Common Card API (Public)
  description: >
    This specification defines a common card API for payment cards used in
    Switzerland. The API is supposed to be used by third parties to retrieve
    payment card information for scheme-based debit, credit or prepaid cards
    (read only).
  contact:
    email: info@common-api.ch
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://card.common-api.ch
externalDocs:
  description: Find out more about SFTI API specifications
  url: https://www.common-api.ch

tags:
  - name: Cards
    description: Operations for retrieving information about payment cards.
  - name: Card-tokens
    description: >-
      Operations for retrieving information about tokens associated with payment
      cards.
  - name: Transactions
    description: >-
      Operations for retrieving information about transactions and
      authorizations done with payment cards or tokens.

security:
  - ApiKeyAuth: []
  - OAuth2:
      - read
      - write

paths:
  /cards:
    get:
      summary: Provides a list of cards which match the provided query parameters.
      description: >
        This operation enables the retrieval of a list of payment cards. Payment
        cards can be physical or virtual cards. In order to prevent API consumers
        from having to fulfill PCI DSS requirements, no full PAN or other data
        relevant for this regulation are included. The API consumer is expected to
        have a non-card related identifier for the customer for whom data should be
        returned (e.g. card account number, bank account number).
      tags:
        - Cards
      parameters:
        - $ref: './components/parameters/query/card_status.yaml'
        - $ref: './components/parameters/query/cursor.yaml'
        - $ref: './components/parameters/query/limit.yaml'
        - $ref: './components/parameters/header/client.yaml'
        - $ref: './components/parameters/header/correlation.yaml'
        - $ref: './components/parameters/header/agent.yaml'
      responses:
        '200':
          $ref: './components/responses/200_cards.yaml'
        '400':
          $ref: './components/responses/400_standard.yaml'
        '500':
          $ref: './components/responses/500_standard.yaml'

  /cards/{cardId}:
      get:
        summary: Provides a single card which matches the id.
        description: >
          This operation enables the retrieval of a single payment card when the cardId is already known.
          The cardId must be retrieved with the GET /cards operation before or stored locally at the API consumer.
        tags:
          - Cards
        parameters:
          - $ref: './components/parameters/path/cardId.yaml'
          - $ref: './components/parameters/header/client.yaml'
          - $ref: './components/parameters/header/correlation.yaml'
          - $ref: './components/parameters/header/agent.yaml'
        responses:
          '200':
            $ref: './components/responses/200_cards_{cardId}.yaml'
          '400':
            $ref: './components/responses/400_standard.yaml'
          '500':
            $ref: './components/responses/500_standard.yaml'

  /card-tokens:
    get:
      summary: Provides a list of card tokens which are associated with a card.
      description: >
        This operation enables the retrieval of a list of tokens associated with a payment card.
        The tokens can be filtered further by status.
        Tokens are representations of a payment card used in specific wallets , wearables or merchants.
      tags:
        - Card-tokens
      parameters:
        - $ref: './components/parameters/query/card_id.yaml'
        - $ref: './components/parameters/query/token_status.yaml'
        - $ref: './components/parameters/query/cursor.yaml'
        - $ref: './components/parameters/query/limit.yaml'
        - $ref: './components/parameters/header/client.yaml'
        - $ref: './components/parameters/header/correlation.yaml'
        - $ref: './components/parameters/header/agent.yaml'
      responses:
        '200':
          $ref: './components/responses/200_card-tokens.yaml'
        '400':
          $ref: './components/responses/400_standard.yaml'
        '500':
          $ref: './components/responses/500_standard.yaml'

  /card-tokens/{tokenId}:
    get:
      summary: Provides a single token which matches the cardId and tokenId
      description: >
        This operation enables the retrieval of a single token when the cardId and tokenId are already known.
        The identifiers must be retrieved with the GET /cards/{cardId}/card-tokens operation before or stored locally at the API consumer.
      tags:
        - Card-tokens
      parameters:
          - $ref: './components/parameters/path/tokenId.yaml'
          - $ref: './components/parameters/header/client.yaml'
          - $ref: './components/parameters/header/correlation.yaml'
          - $ref: './components/parameters/header/agent.yaml'
      responses:
        '200':
          $ref: './components/responses/200_card-tokens_{tokenId}.yaml'
        '400':
          $ref: './components/responses/400_standard.yaml'
        '500':
          $ref: './components/responses/500_standard.yaml'

  /card-transactions:
    get:
      summary: Provides a list of transactions which match the provided query parameters.
      description: >
        This operation enables the retrieval of a list of transactions performed with a payment card or token.
        Different query parameters are provided to support an efficient retrieval of individual transactions.
        With the Level 1 of the Common Card API only card-based financial transactions are included.
      tags:
        - Transactions
      parameters:
        - $ref: './components/parameters/query/authorization_reference.yaml'
        - $ref: './components/parameters/query/clearing_reference.yaml'
        - $ref: './components/parameters/query/card_id.yaml'
        - $ref: './components/parameters/query/token_id.yaml'
        - $ref: './components/parameters/query/from_date.yaml'
        - $ref: './components/parameters/query/to_date.yaml'
        - $ref: './components/parameters/query/status.yaml'
        - $ref: './components/parameters/query/original_currency.yaml'
        - $ref: './components/parameters/query/cursor.yaml'
        - $ref: './components/parameters/query/limit.yaml'
        - $ref: './components/parameters/header/client.yaml'
        - $ref: './components/parameters/header/correlation.yaml'
        - $ref: './components/parameters/header/agent.yaml'
      responses:
        '200':
          $ref: './components/responses/200_card-tokens_{tokenId}.yaml'
        '400':
          $ref: './components/responses/400_standard.yaml'
        '500':
          $ref: './components/responses/500_standard.yaml'

  /card-transactions/{transactionId}:
    get:
      summary: Provides a single transaction which matches the transactionId
      description: >
        This operation enables the retrieval of a single transaction when the transactionId is already known.
        The transactionId must be retrieved with the GET /card-transactions operation before or stored locally at the API consumer.
      tags:
        - Transactions
      parameters:
        - $ref: './components/parameters/path/transactionId.yaml'
        - $ref: './components/parameters/header/client.yaml'
        - $ref: './components/parameters/header/correlation.yaml'
        - $ref: './components/parameters/header/agent.yaml'
      responses:
        '200':
          $ref: './components/responses/200_card-transactions_{transactionId}.yaml'
        '400':
          $ref: './components/responses/400_standard.yaml'
        '500':
          $ref: './components/responses/500_standard.yaml'
