openapi: 3.1.0
info:
  version: 1.0.0
  title: event-notification plugin
  description: |
    This OAS 3.1 specification defines the SFTI Event Notification API standard for secure, and standardized event-based communication
    between financial ecosystem participants. As a cross-stream specification, it provides a generic event notification
    framework used across multiple SFTI repositories, while the stream-specific event types and payload definitions are defined
    and maintained within the respective stream repositories.

    This specification is semantically equivalent to the SPI specifications defined in eventNotificationAPI.yaml and
    eventNotificationWebhookAPI.yaml, but consolidated into a single file to leverage the enhanced capabilities of the OpenAPI 3.1 standard.
  contact:
    email: info@common-api.ch
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://webhook-notification.common-api.ch
externalDocs:
  description: Find out more about SFTI API specifications.
  url: https://www.common-api.ch
tags:
  - name: event subscriptions
    description: |
      Event subscription operations in the context of OAuth2 consent authentication. One subscription is bound to exactly
      one consent and supports create, retrieve, update and delete operations. Multiple event types are managed within the single
      subscription resource.
  - name: event notifications aggregated polling
    description: |
      Aggregated polling operations in the context of Service User authentication, used for catch-up retrieval of event notifications.
security: []
webhooks:
  event-notification:
    $ref: ./webhooks/event-notifications.yaml
paths:
  /event-subscriptions:
    $ref: ./components/paths/event-subscriptions.yaml
  /event-subscriptions/{eventSubscriptionId}:
    $ref: ./components/paths/event-subscriptions_{eventSubscriptionId}.yaml
  /event-subscriptions/{eventSubscriptionId}/event-notifications:
    $ref: ./components/paths/event-subscriptions_{eventSubscriptionId}_event-notifications.yaml
components:
  schemas: {}
  responses: {}
  parameters: {}
  headers: {}
  securitySchemes: {}
  