openapi: 3.1.0
info:
  version: 0.8.0
  title: Common Card API (Public)
  description: |
    This specification defines a common card API for payment cards used in
    Switzerland. The API is supposed to be used by third parties to retrieve
    payment card information for scheme-based debit, credit or prepaid cards
    (read only).
  contact:
    email: info@common-api.ch
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://card.common-api.ch
externalDocs:
  description: Find out more about SFTI API specifications
  url: https://www.common-api.ch

tags:
  - name: Cards
    description: Operations for retrieving information about payment cards.
  - name: Card-tokens
    description: |
      Operations for retrieving information about tokens associated with payment
      cards.
  - name: Transactions
    description: |
      Operations for retrieving information about transactions and
      authorizations done with payment cards or tokens.

security:
  - ApiKeyAuth: []
  - OAuth2:
      - read
      - write

paths:
  /cards:
    get:
      summary: Provides a list of cards which match the provided query parameters.
      description: |
        This operation enables the retrieval of a list of payment cards. Payment
        cards can be physical or virtual cards. In order to prevent API consumers
        from having to fulfill PCI DSS requirements, no full PAN or other data
        relevant for this regulation are included. The API consumer is expected to
        have a non-card related identifier for the customer for whom data should be
        returned (e.g. card account number, bank account number).
      tags:
        - Cards
      parameters:
        - $ref: './components/parameters/query/card_status.yaml'
        - $ref: './components/parameters/query/cursor.yaml'
        - $ref: './components/parameters/query/limit.yaml'
        - $ref: './components/parameters/header/client.yaml'
        - $ref: './components/parameters/header/correlation.yaml'
        - $ref: './components/parameters/header/agent.yaml'
      responses:
        '200':
          description: |
            Payment cards were found which match the query parameters. If no cards
            matched the parameters or access rights are missing, an empty list is
            returned.
          headers:
            X-Correlation-ID:
              $ref: './components/headers/X-Correlation-ID.yaml'
            X-Next-Cursor:
              $ref: './components/headers/X-Next-Cursor.yaml'
          content:
            application/json:
              schema:
                type: object
                required:
                  - cards
                properties:
                  cards:
                    type: array
                    items:
                      $ref: './components/schemas/CardDetails.yaml'
        '400':
          $ref: './components/responses/standard400.yaml'
        '500':
          $ref: './components/responses/standard500.yaml'

  /cards/{cardId}:
    get:
      summary: Provides a single card which matches the id.
      description: |
        This operation enables the retrieval of a single payment card when the cardId is already known.
        The cardId must be retrieved with the GET /cards operation before or stored locally at the API consumer.
      tags:
        - Cards
      parameters:
        - $ref: './components/parameters/path/cardId.yaml'
        - $ref: './components/parameters/header/client.yaml'
        - $ref: './components/parameters/header/correlation.yaml'
        - $ref: './components/parameters/header/agent.yaml'
      responses:
        '200':
          description: Single payment card was found. If the cardId was not found, a 400 is returned.
          headers:
            X-Correlation-ID:
              $ref: './components/headers/X-Correlation-ID.yaml'
          content:
            application/json:
              schema:
                $ref: './components/schemas/CardDetails.yaml'
        '400':
          $ref: './components/responses/standard400.yaml'
        '500':
          $ref: './components/responses/standard500.yaml'

  /card-tokens:
    get:
      summary: Provides a list of card tokens which are associated with a card.
      description: |
        This operation enables the retrieval of a list of tokens associated with a payment card.
        The tokens can be filtered further by status.
        Tokens are representations of a payment card used in specific wallets , wearables or merchants.
      tags:
        - Card-tokens
      parameters:
        - $ref: './components/parameters/query/card_id.yaml'
        - $ref: './components/parameters/query/token_status.yaml'
        - $ref: './components/parameters/query/cursor.yaml'
        - $ref: './components/parameters/query/limit.yaml'
        - $ref: './components/parameters/header/client.yaml'
        - $ref: './components/parameters/header/correlation.yaml'
        - $ref: './components/parameters/header/agent.yaml'
      responses:
        '200':
          description: |
            Card tokens were found which match the query parameters.
            If no card tokens matched the parameters or access rights are missing, an empty list is returned.
          headers:
            X-Correlation-ID:
              $ref: './components/headers/X-Correlation-ID.yaml'
            X-Next-Cursor:
              $ref: './components/headers/X-Next-Cursor.yaml'
          content:
            application/json:
              schema:
                type: object
                required:
                  - card_tokens
                properties:
                  card_tokens:
                    type: array
                    items:
                      $ref: './components/schemas/CardTokenDetails.yaml'
        '400':
          $ref: './components/responses/standard400.yaml'
        '500':
          $ref: './components/responses/standard500.yaml'

  /card-tokens/{tokenId}:
    get:
      summary: Provides a single token which matches the cardId and tokenId
      description: |
        This operation enables the retrieval of a single token when the cardId and tokenId are already known.
        The identifiers must be retrieved with the GET /cards/{cardId}/card-tokens operation before or stored locally at the API consumer.
      tags:
        - Card-tokens
      parameters:
        - $ref: './components/parameters/path/tokenId.yaml'
        - $ref: './components/parameters/header/client.yaml'
        - $ref: './components/parameters/header/correlation.yaml'
        - $ref: './components/parameters/header/agent.yaml'
      responses:
        '200':
          description: Single token was found. If the tokenId was not found, a 400 is returned.
          headers:
            X-Correlation-ID:
              $ref: './components/headers/X-Correlation-ID.yaml'
          content:
            application/json:
              schema:
                $ref: './components/schemas/CardTokenDetails.yaml'
        '400':
          $ref: './components/responses/standard400.yaml'
        '500':
          $ref: './components/responses/standard500.yaml'

  /card-transactions:
    get:
      summary: Provides a list of transactions which match the provided query parameters.
      description: |
        This operation enables the retrieval of a list of transactions performed with a payment card or token.
        Different query parameters are provided to support an efficient retrieval of individual transactions.
        With the Level 1 of the Common Card API only card-based financial transactions are included.
      tags:
        - Transactions
      parameters:
        - $ref: './components/parameters/query/authorization_reference.yaml'
        - $ref: './components/parameters/query/clearing_reference.yaml'
        - $ref: './components/parameters/query/card_id.yaml'
        - $ref: './components/parameters/query/token_id.yaml'
        - $ref: './components/parameters/query/from_date.yaml'
        - $ref: './components/parameters/query/to_date.yaml'
        - $ref: './components/parameters/query/status.yaml'
        - $ref: './components/parameters/query/original_currency.yaml'
        - $ref: './components/parameters/query/cursor.yaml'
        - $ref: './components/parameters/query/limit.yaml'
        - $ref: './components/parameters/header/client.yaml'
        - $ref: './components/parameters/header/correlation.yaml'
        - $ref: './components/parameters/header/agent.yaml'
      responses:
        '200':
          description: |
            Transactions were found which match the query parameters. If no transactions matched the parameters or access rights are missing,
            an empty list is returned.
          headers:
            X-Correlation-ID:
              $ref: './components/headers/X-Correlation-ID.yaml'
            X-Next-Cursor:
              $ref: './components/headers/X-Next-Cursor.yaml'
          content:
            application/json:
              schema:
                type: object
                required:
                  - card-transactions
                properties:
                  card-transactions:
                    type: array
                    items:
                      $ref: './components/schemas/TransactionDetails.yaml'
        '400':
          $ref: './components/responses/standard400.yaml'
        '500':
          $ref: './components/responses/standard500.yaml'

  /card-transactions/{transactionId}:
    get:
      summary: Provides a single transaction which matches the transactionId
      description: |
        This operation enables the retrieval of a single transaction when the transactionId is already known.
        The transactionId must be retrieved with the GET /card-transactions operation before or stored locally at the API consumer.
      tags:
        - Transactions
      parameters:
        - $ref: './components/parameters/path/transactionId.yaml'
        - $ref: './components/parameters/header/client.yaml'
        - $ref: './components/parameters/header/correlation.yaml'
        - $ref: './components/parameters/header/agent.yaml'
      responses:
        '200':
          description: Single token was found. If the transactionId was not found, a 400 is returned.
          headers:
            X-Correlation-ID:
              $ref: './components/headers/X-Correlation-ID.yaml'
          content:
            application/json:
              schema:
                $ref: './components/schemas/TransactionDetails.yaml'
        '400':
          $ref: './components/responses/standard400.yaml'
        '500':
          $ref: './components/responses/standard500.yaml'

components:
  schemas:
    CardDetails:
      $ref: './components/schemas/CardDetails.yaml'

    CardTokenDetails:
      $ref: './components/schemas/CardTokenDetails.yaml'

    TransactionDetails:
      $ref: './components/schemas/TransactionDetails.yaml'

    ContractReference:
      $ref: './components/schemas/ContractReference.yaml'

    PersonReference:
      $ref: './components/schemas/PersonReference.yaml'

    CardId:
      $ref: './components/schemas/CardId.yaml'

    EmbossingLine1:
      $ref: './components/schemas/EmbossingLine1.yaml'

    EmbossingLine2:
      $ref: './components/schemas/EmbossingLine2.yaml'

    Pan4Digits:
      $ref: './components/schemas/Pan4Digits.yaml'

    ExpiryDate:
      $ref: './components/schemas/ExpiryDate.yaml'

    InitialIssuingDate:
      $ref: './components/schemas/InitialIssuingDate.yaml'

    CardStatus:
      $ref: './components/schemas/CardStatus.yaml'

    CardAccountCurrency:
      $ref: './components/schemas/CardAccountCurrency.yaml'

    Image:
      $ref: './components/schemas/Image.yaml'

    ProductCode:
      $ref: './components/schemas/ProductCode.yaml'

    ProductName:
      $ref: './components/schemas/ProductName.yaml'

    Scheme:
      $ref: './components/schemas/Scheme.yaml'

    Category:
      $ref: './components/schemas/Category.yaml'

    IssuingType:
      $ref: './components/schemas/IssuingType.yaml'

    ProductType:
      $ref: './components/schemas/ProductType.yaml'

    ProductLine:
      $ref: './components/schemas/ProductLine.yaml'

    CardLimitCycle:
      $ref: './components/schemas/CardLimitCycle.yaml'

    CardLimitDaily:
      $ref: './components/schemas/CardLimitDaily.yaml'

    CardAccountReference:
      $ref: './components/schemas/CardAccountReference.yaml'

    BankAccountReference:
      $ref: './components/schemas/BankAccountReference.yaml'

    IssuerCode:
      $ref: './components/schemas/IssuerCode.yaml'

    IssuerName:
      $ref: './components/schemas/IssuerName.yaml'

    DistributionPartnerCode:
      $ref: './components/schemas/DistributionPartnerCode.yaml'

    DistributionPartnerName:
      $ref: './components/schemas/DistributionPartnerName.yaml'

    Language:
      $ref: './components/schemas/Language.yaml'

    TokenId:
      $ref: './components/schemas/TokenId.yaml'

    TokenPan4Digits:
      $ref: './components/schemas/TokenPan4Digits.yaml'

    WalletCode:
      $ref: './components/schemas/WalletCode.yaml'

    WalletName:
      $ref: './components/schemas/WalletName.yaml'

    TokenRequestorCode:
      $ref: './components/schemas/TokenRequestorCode.yaml'

    TokenRequestorName:
      $ref: './components/schemas/TokenRequestorName.yaml'

    DeviceName:
      $ref: './components/schemas/DeviceName.yaml'

    DeviceType:
      $ref: './components/schemas/DeviceType.yaml'

    FundingCardId:
      $ref: './components/schemas/FundingCardId.yaml'

    TokenStatus:
      $ref: './components/schemas/TokenStatus.yaml'

    TokenIssuingDate:
      $ref: './components/schemas/TokenIssuingDate.yaml'

    TokenScheme:
      $ref: './components/schemas/TokenScheme.yaml'

    TransactionId:
      $ref: './components/schemas/TransactionId.yaml'

    AuthorizationReference:
      $ref: './components/schemas/AuthorizationReference.yaml'

    ClearingReference:
      $ref: './components/schemas/ClearingReference.yaml'

    TransactionDateTime:
      $ref: './components/schemas/TransactionDateTime.yaml'

    ValutaDate:
      $ref: './components/schemas/ValutaDate.yaml'

    StatementDate:
      $ref: './components/schemas/StatementDate.yaml'

    TransactionStatus:
      $ref: './components/schemas/TransactionStatus.yaml'

    ApprovalNumber:
      $ref: './components/schemas/ApprovalNumber.yaml'

    OriginalAmount:
      $ref: './components/schemas/OriginalAmount.yaml'

    OriginalCurrency:
      $ref: './components/schemas/OriginalCurrency.yaml'

    TotalAmount:
      $ref: './components/schemas/TotalAmount.yaml'

    TransactionAmount:
      $ref: './components/schemas/TransactionAmount.yaml'

    TransactionCurrency:
      $ref: './components/schemas/TransactionCurrency.yaml'

    Fees:
      $ref: './components/schemas/Fees.yaml'

    ExchangeRate:
      $ref: './components/schemas/ExchangeRate.yaml'

    ExchangeRateDate:
      $ref: './components/schemas/ExchangeRateDate.yaml'

    Description:
      $ref: './components/schemas/Description.yaml'

    MerchantName:
      $ref: './components/schemas/MerchantName.yaml'

    MerchantCountry:
      $ref: './components/schemas/MerchantCountry.yaml'

    MerchantCity:
      $ref: './components/schemas/MerchantCity.yaml'

    Mcc:
      $ref: './components/schemas/Mcc.yaml'

    MccDescription:
      $ref: './components/schemas/MccDescription.yaml'

    TerminalReference:
      $ref: './components/schemas/TerminalReference.yaml'

    CardAcceptorReference:
      $ref: './components/schemas/CardAcceptorReference.yaml'

    AcquirerReference:
      $ref: './components/schemas/AcquirerReference.yaml'

    Channel:
      $ref: './components/schemas/Channel.yaml'

    TransactionCategory:
      $ref: './components/schemas/TransactionCategory.yaml'

    CardholderReference:
      $ref: './components/schemas/CardholderReference.yaml'

    RelatedTransactionId:
      $ref: './components/schemas/RelatedTransactionId.yaml'

    FeeName:
      $ref: './components/schemas/FeeName.yaml'

    FeePercentage:
      $ref: './components/schemas/FeePercentage.yaml'

    FeeAmount:
      $ref: './components/schemas/FeeAmount.yaml'

    FeeCurrency:
      $ref: './components/schemas/FeeCurrency.yaml'

    Amount:
      $ref: './components/schemas/generic/Amount.yaml'

    Correlation:
      $ref: './components/schemas/generic/Correlation.yaml'

    Currency:
      $ref: './components/schemas/generic/Currency.yaml'

    Date:
      $ref: './components/schemas/generic/Date.yaml'

    DateTime:
      $ref: './components/schemas/generic/DateTime.yaml'

    Id:
      $ref: './components/schemas/generic/Id.yaml'

    CommonErrorResponse:
      $ref: './components/schemas/CommonErrorResponse.yaml'

  parameters:
    cardId:
      $ref: './components/parameters/path/cardId.yaml'

    tokenId:
      $ref: './components/parameters/path/tokenId.yaml'

    transactionId:
      $ref: './components/parameters/path/transactionId.yaml'

    cursor:
      $ref: './components/parameters/query/cursor.yaml'

    limit:
      $ref: './components/parameters/query/limit.yaml'

    card_status:
      $ref: './components/parameters/query/card_status.yaml'

    card_id:
      $ref: './components/parameters/query/card_id.yaml'

    token_status:
      $ref: './components/parameters/query/token_status.yaml'

    authorization_reference:
      $ref: './components/parameters/query/authorization_reference.yaml'

    clearing_reference:
      $ref: './components/parameters/query/clearing_reference.yaml'

    token_id:
      $ref: './components/parameters/query/token_id.yaml'

    from_date:
      $ref: './components/parameters/query/from_date.yaml'

    to_date:
      $ref: './components/parameters/query/to_date.yaml'

    status:
      $ref: './components/parameters/query/status.yaml'

    original_currency:
      $ref: './components/parameters/query/original_currency.yaml'

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: Grants read access
            write: Grants write access

  responses:
    standard400:
      $ref: './components/responses/standard400.yaml'

    standard500:
      $ref: './components/responses/standard500.yaml'

  headers:
    Content-Language:
      $ref: './components/headers/Content-Language.yaml'

    X-Correlation-ID:
      $ref: './components/headers/X-Correlation-ID.yaml'

    X-Next-Cursor:
      $ref: './components/headers/X-Next-Cursor.yaml'