openapi: 3.1.0
info:
  version: 1.0.0
  title: Common Card API
  description: |
    This specification defines a common card API for payment cards used in Switzerland. The API is supposed to be used by third parties to
    retrieve payment card information for scheme-based debit, credit or prepaid cards (read only).
  contact:
    email: info@common-api.ch
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://card.common-api.ch
externalDocs:
  description: Find out more about SFTI API specifications.
  url: https://www.common-api.ch
tags:
  - name: Card-tokens
    description: Operations for retrieving information about tokens associated with payment cards.
  - name: Cards
    description: Operations for retrieving information about payment cards.
  - name: Transactions
    description: Operations for retrieving information about transactions and authorizations done with payment cards or tokens.
security: []
paths:
  /cards:
    get:
      summary: Provides a list of cards which match the provided query parameters
      description: |
        This operation enables the retrieval of a list of payment cards. Payment cards can be physical or virtual cards. In order to prevent
        API consumers from having to fulfill PCI DSS requirements, no full PAN or other data relevant for this regulation are included. The
        API consumer is expected to have a non-card related identifier for the customer for whom data should be returned (e.g. card account
        number, bank account number).
      operationId: listCards
      tags:
        - Cards
      parameters:
        - $ref: ./components/parameters/query/card_status.yaml
        - $ref: ./components/parameters/query/cursor.yaml
        - $ref: ./components/parameters/query/limit.yaml
        - $ref: ./components/parameters/header/client.yaml
        - $ref: ./components/parameters/header/correlation.yaml
        - $ref: ./components/parameters/header/agent.yaml
      responses:
        '200':
          description: |
            Payment cards were found which match the query parameters. If no cards matched the parameters or access rights are missing, an
            empty list is returned.
          headers:
            X-Correlation-ID:
              $ref: ./components/headers/X-Correlation-ID.yaml
            X-Next-Cursor:
              $ref: ./components/headers/X-Next-Cursor.yaml
          content:
            application/json:
              schema:
                type: object
                required:
                  - cards
                properties:
                  cards:
                    type: array
                    items:
                      $ref: ./components/schemas/CardDetails.yaml
        '400':
          $ref: ./components/responses/standard400.yaml
        '500':
          $ref: ./components/responses/standard500.yaml

  /card-accounts:
    x-api-level: 2
    get:
      summary: Provides a list of card accounts which match the provided query parameters
      description: |
        This operation enables the retrieval of a list of card accounts. A card account represents the account to which one or more payment
        cards are linked. In order to prevent API consumers from having to fulfill PCI DSS requirements, no full PAN or other data relevant
        for this regulation are included. The API consumer is expected to have a non-card related identifier for the customer for whom data
        should be returned (e.g. bank account number).
      operationId: listCardAccounts
      tags:
        - Cards
      parameters:
        - $ref: ./components/parameters/query/card_status.yaml # todo
        - $ref: ./components/parameters/query/cursor.yaml
        - $ref: ./components/parameters/query/limit.yaml
        - $ref: ./components/parameters/header/client.yaml
        - $ref: ./components/parameters/header/correlation.yaml
        - $ref: ./components/parameters/header/agent.yaml
      responses:
        '200':
          description: |
            Card accounts were found which match the query parameters. If no card accounts matched the parameters or access rights are missing,
            an empty list is returned.
          headers:
            X-Correlation-ID:
              $ref: ./components/headers/X-Correlation-ID.yaml
            X-Next-Cursor:
              $ref: ./components/headers/X-Next-Cursor.yaml
          content:
            application/json:
              schema:
                type: object
                required:
                  - cardAccounts
                properties:
                  cardAccounts:
                    type: array
                    items:
                      $ref: ./components/schemas/CardDetails.yaml
        '400':
          $ref: ./components/responses/standard400.yaml
        '500':
          $ref: ./components/responses/standard500.yaml
