name: 'SFTI Bundle API specification' 
# caution: do not rename filename as pr workflow depends on its name

on:
  workflow_dispatch:

jobs:
  bundle-api:
    uses: swissfintechinnovations/.github/.github/workflows/reusable-bundle-workflow.yaml@update-actions
    secrets: inherit