name: 'SFTI Lint Specifications: Yaml Compliance'

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      filenames:
        type: string
        default: '*.yaml src/**.yaml'
        description: 'Files to be linted (list of files sperated by a whitespace). Default: *.yaml and src/**.yaml'

jobs:
  yaml-lint:
    uses: swissfintechinnovations/.github/.github/workflows/reusable-lint-yaml-workflow.yaml@main
    with:
      filenames: ${{ github.event.inputs.filenames || '*.yaml src/**.yaml' }}