name: 'SFTI Lint Specifications: Yaml Compliance'

on:
  workflow_dispatch:
    inputs:
      filenames:
        type: string
        default: 'src/**'
        description: 'Files to be linted (list of files sperated by a whitespace). Default: src/**'

jobs:
  yaml-lint:
    uses: swissfintechinnovations/.github/.github/workflows/reusable-lint-yaml-workflow.yaml@main
    with:
      filenames: ${{ github.event.inputs.filenames || 'src/**' }}