name: 'SFTI Lint PRs'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - 'src/**'

jobs:
  bundle-run-status:
    if: ${{ always() }}
    uses: swissfintechinnovations/.github/.github/workflows/reusable-bundle-status-workflow.yaml@main

  yaml-lint-src:
    needs: bundle-run-status
    if: ${{ always() }}
    uses: swissfintechinnovations/.github/.github/workflows/reusable-lint-yaml-workflow.yaml@main
    with:
      filenames: 'src/**.yaml'

  yaml-lint:
    needs: bundle-run-status
    if: ${{ always() }}
    uses: swissfintechinnovations/.github/.github/workflows/reusable-lint-yaml-workflow.yaml@main
    with:
      filenames: '*.yaml'

  openapi-lint:
    needs: bundle-run-status
    if: ${{ always() }}
    uses: swissfintechinnovations/.github/.github/workflows/reusable-lint-openapi-workflow.yaml@main
    with:
      filenames: '*.yaml'