name: 'SFTI Lint PRs'

on:
  workflow_run:
    workflows:
      - 'SFTI Bundle API specification'
    types:
      - completed

jobs:
  bundle-run-status:
    uses: swissfintechinnovations/.github/.github/workflows/reusable-bundle-status-workflow.yaml@main
    with:
      bundle_status: ${{ github.event.workflow_run.conclusion }}

  yaml-lint-src:
    uses: swissfintechinnovations/.github/.github/workflows/reusable-lint-yaml-workflow.yaml@main
    with:
      filenames: 'src/**.yaml'

  yaml-lint:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: swissfintechinnovations/.github/.github/workflows/reusable-lint-yaml-workflow.yaml@main
    with:
      filenames: '*.yaml'

  openapi-lint:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: swissfintechinnovations/.github/.github/workflows/reusable-lint-openapi-workflow.yaml@main
    with:
      filenames: '*.yaml'